dist: bionic
language: go

go:
  - 1.14.1

git:
  depth: 1

notifications:
  email: false

install:
  - # skip
    
script:
  - make all_tests

before_deploy:
  - make build

deploy:
    - provider: releases
      api_key: "$GITHUB_OAUTH_TOKEN"
      file_glob: true
      file: build/*
      skip_cleanup: true
      on:
        all_branches: true


branches:
  except:
    - legacy
    - experimental