dist: bionic
language: go

go:
  - 1.14.1

git:
  depth: 1

notifications:
  email: false

script:
  - make all_tests

before_deploy:
  - make build

deploy:
  - on:
      all_branches: true
    provider: releases
    api_key: "$GITHUB_OAUTH_TOKEN"
    file_glob: true
    file: build/*
    skip_cleanup: true


branches:
  except:
    - legacy
    - experimental