dist: bionic
language: go

go:
  - 1.14.1

git:
  depth: 1

notifications:
  email: false
  pushover:
    api_key: "$PUSHOVER_TOKEN"
    users:
      - "$PUSHOVER_MPLIEGO_TOKEN"
    template: "%{repository_slug} (%{commit}) : %{message} - Build details: %{build_url}"
    on_success: always
    on_failure: always

script:
  - make all_tests

before_deploy:
  - make build

deploy:
    - provider: releases
      api_key: "$GITHUB_TOKEN"
      file_glob: true
      file: build/*
      cleanup: false
      on:
        tags: true

branches:
  except:
    - legacy
    - experimental